import appJSON from '../../../package.json'

export const STORE_SERVICE_REQUEST = `${appJSON.name}/App/STORE_SERVICE_REQUEST`
export const STORE_SERVICE_REQUEST_SUCCESS = `${appJSON.name}/App/STORE_SERVICE_REQUEST_SUCCESS`
export const STORE_SERVICE_REQUEST_ERROR = `${appJSON.name}/App/STORE_SERVICE_REQUEST_ERROR`

export default { STORE_SERVICE_REQUEST, STORE_SERVICE_REQUEST_SUCCESS, STORE_SERVICE_REQUEST_ERROR }
